In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot  as plt 
import seaborn as sns

In [34]:
df =pd.read_csv("../data/Raw_Dataset.csv")
print(df.shape)
df.head()

(51325, 21)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,01-01-2011,06-01-2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,01-01-2011,08-01-2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,01-01-2011,05-01-2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,01-01-2011,05-01-2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,OFF-PA-10001492,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,01-01-2011,08-01-2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,FUR-FU-10003447,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51325 entries, 0 to 51324
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51325 non-null  object
 1   order_date      51325 non-null  object
 2   ship_date       51325 non-null  object
 3   ship_mode       51325 non-null  object
 4   customer_name   51246 non-null  object
 5   segment         51325 non-null  object
 6   state           51325 non-null  object
 7   country         51325 non-null  object
 8   market          51325 non-null  object
 9   region          51325 non-null  object
 10  product_id      51325 non-null  object
 11  category        51325 non-null  object
 12  sub_category    51325 non-null  object
 13  product_name    51325 non-null  object
 14  sales           51325 non-null  object
 15  quantity        51325 non-null  int64
 16  discount        51325 non-null  float64
 17  profit          51311 non-null  float64
 18  shipping_cost   51325 non-null  float64
 19  order_priority  51325 non-null  object
 20  year            51325 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

# Remove ONLY exact duplicates

**NOTE**: one row = one product line within an order.
order_id is expected to repeat. It is NOT a unique row identifier.

The only duplicate you can safely remove without investigation is a row that is identical across every single column. Anything else needs manual inspection first

In [36]:
exact_dupes = df.duplicated().sum()
print("Exact duplicate rows:", exact_dupes)

df = df.drop_duplicates()

print("New shapes:", df.shape)
print("Duplicates remaining:", df.duplicated().sum())

Exact duplicate rows: 54
New shapes: (51271, 21)
Duplicates remaining: 0

In [37]:
check = df[df.duplicated(subset=['order_id', 'product_id'], keep=False)]
check.sort_values('order_id').head(10)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
42816,AG-2014-4840,20-08-2014,25-08-2014,Standard Class,Cynthia Delaney,Home Office,Oran,Algeria,Africa,Africa,TEC-MEM-10002524,Technology,Accessories,"Memorex Mouse, USB",57,2,0.0,10.7400,5.43,High,2014
42826,AG-2014-4840,20-08-2014,25-08-2014,Standard Class,Cynthia Delaney,Home Office,Oran,Algeria,Africa,Africa,TEC-MEM-10002524,Technology,Accessories,"Memorex Mouse, USB",57,2,0.0,10.7400,2.77,High,2014
13766,CA-2012-103135,24-07-2012,28-07-2012,Standard Class,Shirley Schmidt,Home Office,Kentucky,United States,US,South,OFF-BI-10000069,Office Supplies,Binders,"GBC Prepunched Paper, 19-Hole, for Binding Sys...",90,6,0.0,41.4276,12.98,High,2012
13771,CA-2012-103135,24-07-2012,28-07-2012,Standard Class,Shirley Schmidt,Home Office,Kentucky,United States,US,South,OFF-BI-10000069,Office Supplies,Binders,"GBC Prepunched Paper, 19-Hole, for Binding Sys...",135,9,0.0,62.1414,9.60,High,2012
27841,CA-2013-129714,02-09-2013,04-09-2013,First Class,Adam Bellavance,Home Office,New York,United States,US,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,25,2,0.0,11.5432,6.53,Critical,2013
27843,CA-2013-129714,02-09-2013,04-09-2013,First Class,Adam Bellavance,Home Office,New York,United States,US,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,49,4,0.0,23.0864,6.22,Critical,2013
33386,CA-2013-137043,24-12-2013,26-12-2013,Second Class,Logan Currie,Consumer,Virginia,United States,US,South,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",286,3,0.0,83.0502,45.72,High,2013
33383,CA-2013-137043,24-12-2013,26-12-2013,Second Class,Logan Currie,Consumer,Virginia,United States,US,South,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",573,6,0.0,166.1004,56.26,High,2013
21727,CA-2013-140571,16-03-2013,20-03-2013,Standard Class,Sanjit Jacobs,Home Office,Mississippi,United States,US,South,OFF-PA-10001954,Office Supplies,Paper,Xerox 1964,46,2,0.0,21.0128,8.20,High,2013
21722,CA-2013-140571,16-03-2013,20-03-2013,Standard Class,Sanjit Jacobs,Home Office,Mississippi,United States,US,South,OFF-PA-10001954,Office Supplies,Paper,Xerox 1964,320,14,0.0,147.0896,31.86,High,2013

has same order_id but different shipping_cost, thats not a duplicate

In [38]:
df.isnull().sum()

order_id           0
order_date         0
ship_date          0
ship_mode          0
customer_name     79
segment            0
state              0
country            0
market             0
region             0
product_id         0
category           0
sub_category       0
product_name       0
sales              0
quantity           0
discount           0
profit            14
shipping_cost      0
order_priority     0
year               0
dtype: int64

In [39]:
df['customer_name'] = df['customer_name'].fillna("Unknown Custommer")

In [40]:
df[df['profit'].isnull()]

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
65,ID-2011-58670,07-01-2011,11-01-2011,Standard Class,Maribeth Schnelling,Consumer,National Capital,Philippines,APAC,Southeast Asia,TEC-MA-10004482,Technology,Machines,"Panasonic Card Printer, White",388,3,0.25,NaN,26.20,High,2011
160,NI-2011-1670,12-01-2011,16-01-2011,Standard Class,Shaun Chance,Corporate,Lagos,Nigeria,Africa,Africa,OFF-KLE-10001317,Office Supplies,Supplies,"Kleencut Ruler, Easy Grip",5,1,0.70,NaN,0.43,Medium,2011
317,EN-2011-70,24-01-2011,24-01-2011,Same Day,Ann Blume,Corporate,Harjumaa,Estonia,EMEA,EMEA,FUR-HON-10000722,Furniture,Chairs,"Hon Rocking Chair, Adjustable",133,1,0.00,NaN,15.16,Medium,2011
553,IT-2011-1181278,10-02-2011,10-02-2011,Same Day,Paul Lucas,Home Office,Lower Saxony,Germany,EU,Central,OFF-ST-10001554,Office Supplies,Storage,"Tenex File Cart, Industrial",215,4,0.60,NaN,60.85,High,2011
709,IN-2011-78781,21-02-2011,25-02-2011,Standard Class,John Lucas,Consumer,South Australia,Australia,APAC,Oceania,OFF-LA-10000732,Office Supplies,Labels,"Novimex Round Labels, 5000 Label Set",36,6,0.10,NaN,2.54,Medium,2011
822,CA-2011-104269,01-03-2011,06-03-2011,Second Class,Dave Brooks,Consumer,Washington,United States,US,West,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,458,2,0.20,NaN,47.89,Medium,2011
919,CA-2011-117016,04-03-2011,09-03-2011,Standard Class,Sanjit Chand,Consumer,Florida,United States,US,South,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",16,3,0.20,NaN,1.31,Medium,2011
1009,MX-2011-104752,11-03-2011,16-03-2011,Standard Class,Michelle Moray,Consumer,Pinar del Río,Cuba,LATAM,Caribbean,TEC-PH-10004237,Technology,Phones,"Nokia Office Telephone, with Caller ID",43,1,0.00,NaN,2.81,Medium,2011
1228,IT-2011-2306373,25-03-2011,30-03-2011,Second Class,Bruce Degenhardt,Consumer,North Brabant,Netherlands,EU,Central,TEC-PH-10001937,Technology,Phones,"Nokia Audio Dock, Full Size",84,1,0.50,NaN,6.66,Medium,2011
1329,CA-2011-128055,31-03-2011,05-04-2011,Standard Class,Alex Avila,Consumer,California,United States,US,West,OFF-BI-10004390,Office Supplies,Binders,GBC DocuBind 200 Manual Binding Machine,674,2,0.20,NaN,54.96,Medium,2011
1479,CA-2011-153808,06-04-2011,10-04-2011,Second Class,Frank Hawley,Corporate,California,United States,US,West,OFF-AR-10001725,Office Supplies,Art,Boston Home & Office Model 2000 Electric Penci...,71,3,0.00,NaN,8.74,High,2011
1761,SG-2011-6280,22-04-2011,23-04-2011,First Class,Carol Darley,Consumer,Dakar,Senegal,Africa,Africa,OFF-FEL-10000998,Office Supplies,Storage,"Fellowes Box, Single Width",79,4,0.00,NaN,22.35,Critical,2011
1945,CA-2011-5840,03-05-2011,09-05-2011,Standard Class,Cindy Chapman,Consumer,Ontario,Canada,Canada,Canada,TEC-STA-10004181,Technology,Machines,"StarTech Inkjet, Durable",600,2,0.00,NaN,52.98,Medium,2011
2132,CA-2011-139017,11-05-2011,17-05-2011,Standard Class,Raymond Messe,Consumer,Texas,United States,US,Central,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,47,2,0.20,NaN,6.52,Low,2011

In [51]:
print(df['sales'].dtype)
print(df['profit'].dtype)

object
float64

In [52]:
# remove commas and convert to proper number
df['sales'] = df['sales'].astype(str).str.replace(',', '', regex=False)
df['sales'] = pd.to_numeric(df['sales'], errors='coerce')

# do the same check for other numeric columns just in case
for col in ['quantity', 'discount', 'profit', 'shipping_cost']:
    print(col, df[col].dtype)

quantity int64
discount float64
profit float64
shipping_cost float64

In [53]:
df['profit_estimated'] = df['profit'].isnull()  # flag BEFORE filling

margin_by_subcat = df.dropna(subset=['profit']).groupby('sub_category').apply(
    lambda x: x['profit'].sum() / x['sales'].sum()
)

def fill_profit(row):
    if pd.isnull(row['profit']):
        return row['sales'] * margin_by_subcat.get(row['sub_category'], 0)
    return row['profit']

df['profit'] = df.apply(fill_profit, axis=1)

C:\Users\Aditya Gupta\AppData\Local\Temp\ipykernel_10844\117231642.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  margin_by_subcat = df.dropna(subset=['profit']).groupby('sub_category').apply(

In [54]:
df.isnull().sum()

order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_name       0
segment             0
state               0
country             0
market              0
region              0
product_id          0
category            0
sub_category        0
product_name        0
sales               0
quantity            0
discount            0
profit              0
shipping_cost       0
order_priority      0
year                0
profit_estimated    0
dtype: int64

# Cleaning text col

In [45]:
text_cols = ['ship_mode', 'segment', 'state', 'country', 'market', 
             'region', 'category', 'sub_category', 'order_priority']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

In [46]:
for col in text_cols:
    print(col, df[col].unique())
    print()

ship_mode ['Standard Class' 'Second Class' 'Same Day' 'First Class']

segment ['Consumer' 'Home Office' 'Corporate']

state ['Constantine' 'New South Wales' 'Budapest' ... 'Karaman' 'Sikasso'
 'Atsimo-Andrefana']

country ['Algeria' 'Australia' 'Hungary' 'Sweden' 'Canada' 'New Zealand' 'Iraq'
 'Philippines' 'United Kingdom' 'Malaysia' 'Guatemala' 'Iran' 'Thailand'
 'Tanzania' 'Brazil' 'Mexico' 'Cuba' 'France' 'United States' 'Japan'
 'Sudan' 'Taiwan' 'Indonesia' 'Vietnam' 'Angola' 'China' 'Mozambique'
 'Lebanon' 'Singapore' 'Netherlands' 'Nigeria' 'Egypt' 'Venezuela'
 'South Africa' 'Spain' 'India' 'Turkey' 'Austria' 'Italy' 'Germany'
 'Nicaragua' 'Dominican Republic' 'El Salvador' 'Denmark' 'Saudi Arabia'
 'Zambia' 'Myanmar (Burma)' 'Russia' 'Mongolia' 'Belgium' 'Kenya'
 'Colombia' 'Estonia' 'Madagascar' 'Portugal' 'Morocco' 'Sierra Leone'
 'Norway' 'Central African Republic' 'Czech Republic' 'Benin' 'Bangladesh'
 'Panama' 'Chile' 'South Korea' 'Switzerland' 'Moldova' 'Uganda'
 'Zimbabwe' 'Niger' 'Senegal' 'Hong Kong'
 'Democratic Republic Of The Congo' 'Poland' 'Ireland' 'Pakistan'
 'Azerbaijan' 'Ukraine' 'Albania' 'Romania' 'Honduras' 'Israel' 'Cameroon'
 'Cambodia' 'Georgia' 'Argentina' 'Finland' 'Lithuania' 'Peru' 'Somalia'
 'Haiti' "Cote D'Ivoire" 'Afghanistan' 'Guinea' 'Liberia' 'South Sudan'
 'Turkmenistan' 'Kazakhstan' 'Lesotho' 'Burundi' 'Qatar' 'Bulgaria'
 'Martinique' 'Croatia' 'Ghana' 'Rwanda' 'Ecuador' 'Paraguay' 'Ethiopia'
 'Syria' 'Tajikistan' 'Slovakia' 'Belarus' 'Papua New Guinea' 'Togo'
 'Libya' 'Djibouti' 'Yemen' 'United Arab Emirates' 'Barbados' 'Uzbekistan'
 'Jamaica' 'Bolivia' 'Uruguay' 'Republic Of The Congo' 'Swaziland'
 'Kyrgyzstan' 'Guinea-Bissau' 'Bosnia And Herzegovina' 'Tunisia' 'Armenia'
 'Mali' 'Jordan' 'Trinidad And Tobago' 'Namibia' 'Gabon' 'Macedonia'
 'Nepal' 'Mauritania' 'Guadeloupe' 'Sri Lanka' 'Chad' 'Eritrea' 'Bahrain'
 'Equatorial Guinea' 'Slovenia' 'Montenegro']

market ['Africa' 'Apac' 'Emea' 'Eu' 'Canada' 'Latam' 'Us']

region ['Africa' 'Oceania' 'Emea' 'North' 'Canada' 'Southeast Asia' 'Central'
 'South' 'Caribbean' 'North Asia' 'East' 'West' 'Central Asia']

category ['Office Supplies' 'Furniture' 'Technology']

sub_category ['Storage' 'Supplies' 'Paper' 'Furnishings' 'Machines' 'Appliances'
 'Copiers' 'Chairs' 'Tables' 'Bookcases' 'Phones' 'Accessories' 'Labels'
 'Art' 'Envelopes' 'Fasteners' 'Binders']

order_priority ['Medium' 'High' 'Critical' 'Low']

# Fixing Dates

In [47]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce', dayfirst=True)
df['ship_date'] = pd.to_datetime(df['ship_date'], errors='coerce', dayfirst=True)

print(df['order_date'].isnull().sum())
print(df['ship_date'].isnull().sum())

0
0

In [48]:
# logic check: ship_date should never be before order_date
bad_dates = df[df['ship_date'] < df['order_date']]
print("Rows where ship_date is before order_date:", len(bad_dates))
bad_dates.head()

Rows where ship_date is before order_date: 0

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_name, segment, state, country, market, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit, shipping_cost, order_priority, year, profit_estimated]
Index: []

In [49]:
df[['sales', 'quantity', 'discount', 'profit', 'shipping_cost']].describe()

           quantity      discount        profit  shipping_cost
count  51271.000000  51271.000000  51257.000000   51271.000000
mean       3.476468      0.142920     28.630189      26.365625
std        2.278474      0.212283    174.463151      57.287201
min        1.000000      0.000000  -6599.978000       0.000000
25%        2.000000      0.000000      0.000000       2.610000
50%        3.000000      0.000000      9.240000       7.790000
75%        5.000000      0.200000     36.807000      24.445000
max       14.000000      0.850000   8399.976000     933.570000

In [55]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str).str.strip()

In [56]:
print("Final shape:", df.shape)
df.isnull().sum()

Final shape: (51271, 22)

order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_name       0
segment             0
state               0
country             0
market              0
region              0
product_id          0
category            0
sub_category        0
product_name        0
sales               0
quantity            0
discount            0
profit              0
shipping_cost       0
order_priority      0
year                0
profit_estimated    0
dtype: int64

In [57]:
df.to_csv("Cleaned_data.csv", index=False)

In [ ]:
from pathlib import Path

def print_tree(path, max_depth=1, prefix="", depth=0):
    path = Path(path)
    items = sorted(path.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))

    for i, item in enumerate(items):
        connector = "└── " if i == len(items) - 1 else "├── "
        print(prefix + connector + item.name)

        if item.is_dir() and depth < max_depth:
            extension = "    " if i == len(items) - 1 else "│   "
            print_tree(item, max_depth, prefix + extension, depth + 1)

# Change "." to your project path if needed
print(Path(".").resolve().name)
print_tree(".", max_depth=1)

notebooks
├── 01_data_cleaning.ipynb
└── Cleaned_data.csv